# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: ZTljYWViNDk4MmJlYTU2ZWI1NGQzMmU2YjMzMTY2NzlhNzk1ZWVhYjE1Nzg4YjFkMDJhN2VhNmZiODEzNTQxNWYwZGZkMDNjZDQ1OTVlZDhlNWI1YWNiMTA2MWRmYWI4MzAxYjIxZTRhOTI2YmE2ZDM5MmIyMjVhYmIwOTJmNjA=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
